In [5]:
import numpy as np
import time 
import sys

In [4]:
a = np.array([1,2,3])
a[0]

1

In [3]:
# 3 main benefits of numpy array over a python list
# less memory
# fast
# convinient

In [6]:
l = range(1000)
print(sys.getsizeof(5)*len(l))

28000


In [7]:
array = np.arange(1000)
print(array.size*array.itemsize)

8000


In [8]:
size = 1000
l1 = range(size)
l2 = range(size)
a1= np.arange(size)
a2 = np.arange(size)

start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("Python list took :", (time.time() - start) *1000)

#numpyarray
start = time.time()
result = a1+a2
print("numpy took:", (time.time()-start)*1000)


Python list took : 0.2963542938232422
numpy took: 31.003952026367188


In [12]:
#a1/a2
#a1*a2

In [14]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
a.ndim

2

In [16]:
a.itemsize

8

In [17]:
a.dtype

dtype('int64')

In [18]:
a = np.array([[1,2],[3,4],[5,6]], dtype=np.float64)
a.dtype


dtype('float64')

In [20]:
a.shape

(3, 2)

In [21]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.arange(1,5)

array([1, 2, 3, 4])

In [25]:
np.arange(1,5,2) #step by 2 

array([1, 3])

In [26]:
np.linspace(1,5,10) 
# 10 numbers between 1 and 5 

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [27]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [28]:
a.shape

(3, 2)

In [29]:
a.reshape(2,3)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [30]:
a.ravel() # make array one dimension -- it will return new array

array([1., 2., 3., 4., 5., 6.])

In [31]:
a.min()

1.0

In [32]:
a.max()

6.0

In [33]:
a.sum(axis=0) # axis=0 columns 

array([ 9., 12.])

In [34]:
a.sum(axis=1) #axis=1 rows

array([ 3.,  7., 11.])

In [35]:
np.std(a)

1.707825127659933

In [36]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a.dot(b)

array([[19, 22],
       [43, 50]])

In [37]:
# slicing/stacking , indexing

In [38]:
n = [5,6,7]
n[0:2]

[5, 6]

In [39]:
a = np.array([6,5,8])
a[0:2]

array([6, 5])

In [41]:
a = np.array([[1,2],[3,4],[5,6]])
a[1,1]


4

In [42]:
a[-1]

array([5, 6])

In [44]:
a[-1,0:1]

array([5])

In [45]:
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)

In [46]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [47]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [48]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [49]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [50]:
a=np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [51]:
np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [53]:
np.vsplit(a,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [54]:
b = a>4
b

array([[False, False, False, False, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True]])

In [55]:
a[b] ## boolean indexing - print which is true in b 

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])